export const GMI_BASE_URL=(process.env.GMI_BASE_URL||'https://api.gmi-serving.com/v1').replace(/\/$/,'');
export const GMI_MODEL=process.env.GMI_MODEL||'MiniMaxAI/MiniMax-M3';
export const AVOMIEZ_LOCK=`AvoMiez is a photorealistic orange/golden tabby domestic cat with darker tabby stripes, white chest, white muzzle and white paws, expressive amber-green eyes and natural feline anatomy. Signature accessories: glossy black wraparound visor, thick gold chain, round gold medallion engraved AVOMIEZ. Personality: confident, charismatic, deadpan, slightly absurd. Preserve feline anatomy and visual identity; no bipedal humanization unless explicitly requested.`;
export function configured(){const k=process.env.GMI_API_KEY;return Boolean(k&&k!=='your_gmi_api_key_here')}
function requireKey(){if(!configured())throw new Error('GMI_API_KEY is not configured in Vercel Environment Variables.');return process.env.GMI_API_KEY}
export function extractJson(text){if(typeof text!=='string')return text;const c=text.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');try{return JSON.parse(c)}catch{}const a=c.indexOf('{'),b=c.lastIndexOf('}');if(a!==-1&&b>a){try{return JSON.parse(c.slice(a,b+1))}catch{}}throw new Error('MiniMax returned text that could not be parsed as JSON.')}
export async function callM3({system,user,messages,temperature=.6,maxTokens=2600}){const r=await fetch(`${GMI_BASE_URL}/chat/completions`,{method:'POST',headers:{Authorization:`Bearer ${requireKey()}`,'Content-Type':'application/json'},body:JSON.stringify({model:GMI_MODEL,messages:messages||[{role:'system',content:system},{role:'user',content:user}],temperature,top_p:.95,max_tokens:maxTokens,response_format:{type:'json_object'},stream:false})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p?.error?.message||p?.message||`GMI request failed (${r.status})`);const content=p?.choices?.[0]?.message?.content;if(!content)throw new Error('GMI returned no assistant content.');return{data:extractJson(content),usage:p.usage||null,model:p.model||GMI_MODEL}}
export function send(res,status,data){res.status(status).setHeader('Cache-Control','no-store').json(data)}
export function enforcePost(req,res){if(req.method!=='POST'){send(res,405,{error:'Method not allowed'});return false}return true}
