import{AVOMIEZ_LOCK,callM3,send}from'./gmi.js';
import{resolveTargetModel,splitDurations,modelPromptGuidance,MODEL_PROFILES_VERIFIED_AT}from'./video-models.js';
import{enforceVideoPromptLimit}from'./prompt-limit.js';

const TYPES=['character','world','outfit','prop','relation'];
const cleanType=v=>TYPES.includes(String(v||'').toLowerCase())?String(v).toLowerCase():'prop';
const refSystem=`You are the Reference Builder inside AvoMiez Director V3.3. Design practical visual-reference packs for recurring AI-video stories and micro-dramas. ${AVOMIEZ_LOCK}\nChoose only references that genuinely improve continuity across many clips. Favor human-led drama when requested; AvoMiez may be absent, cameo, side character, co-lead or lead. Return JSON only.`;
const microSystem=`You are the Micro Drama Studio inside AvoMiez Director V3.3. Create mobile-first 9:16 serialized micro-dramas with strong human-led character conflict, secrets, reversals, cliffhangers and visual continuity. ${AVOMIEZ_LOCK}\nAvoMiez may be absent, cameo, sidekick, co-lead or lead depending on the creator setting. Do not force him into every beat. Episodes may be 30-120 seconds and must be divided into target-model-compatible generation clips. Never claim guaranteed virality. Return JSON only.`;

function refContext(b){return`SERIES / STORY PREMISE:\n${String(b.story||'').trim()}\nGENRE: ${b.genre||'drama'}\nTONE: ${b.tone||'balanced'}\nHUMAN FOCUS: ${b.humanFocus||'human leads'}\nAVOMIEZ ROLE: ${b.avomiezRole||'side character / cameo'}\nSERIES SCALE: ${b.seriesScale||'multi-episode short-form series'}\nCREATOR NOTES: ${b.notes||'none'}`}
function suggestRefs(b){return`${refContext(b)}\n\nSuggest a lean REFERENCE FOUNDATION. Think CHARACTER, WORLD, OUTFIT, PROP, RELATION. Human leads get stable master sheets when recurring. AvoMiez only if visually relevant. Recurring locations get world sheets; one-off locations usually do not. Outfit sheets are for repeated/signature states. Props only if story-critical. Relation sheets are for stable height/proportion/chemistry/blocking of recurring pairs. Prefer 5-10 strong references.\n\nReturn exactly {"packTitle":"","strategy":"2-4 concise sentences","suggested":[{"id":"ref-1","name":"","type":"character|world|outfit|prop|relation","recurring":true,"importance":"critical|high|medium|optional","reason":"","notes":"visual locks","videoUse":"how later video prompts should use it"}],"missingQuestions":["only material consistency questions"]}.`}
function buildRefs(b){const refs=(Array.isArray(b.references)?b.references:[]).slice(0,12).map((r,i)=>({id:r.id||`ref-${i+1}`,name:r.name||`Reference ${i+1}`,type:cleanType(r.type),recurring:r.recurring!==false,importance:r.importance||'high',notes:r.notes||'',reason:r.reason||'',videoUse:r.videoUse||''}));return`${refContext(b)}\n\nREFERENCE ENTRIES:\n${JSON.stringify(refs)}\n\nWrite one copy-ready IMAGE-GENERATION PROMPT for every entry. CHARACTER: photorealistic master sheet, same identity in every panel, front/3/4/side/full-body/face close-up, neutral expression plus one useful story expression, neutral studio background. WORLD: recurring environment board with establishing wide, spatial medium view and key details; preserve layout. OUTFIT: assigned character identity, front/3/4/back, materials/fit/accessories/footwear/state, do not redesign person. PROP: hero view, side/details/scale and distinctive features. RELATION: two recurring characters together with stable height/proportion/identity, neutral two-shot plus one story-relevant blocking pose. AvoMiez keeps natural feline anatomy and established identity/accessories unless a temporary costume is explicitly requested.\n\nReturn exactly {"packTitle":"","items":[{"id":"","name":"","type":"character|world|outfit|prop|relation","imagePrompt":"complete prompt","consistencyLock":"short reusable visual lock","videoUseHint":"short mapping instruction","suggestedFileName":"safe-short-filename.png"}]}.`}

export async function handleReferenceAction(b,res){
  if(!String(b.story||'').trim())return send(res,400,{error:'Add a series/story premise first.'});
  if(b.action==='reference-suggest'){
    const r=await callM3({system:refSystem,user:suggestRefs(b),temperature:.45,maxTokens:2600});
    const suggested=Array.isArray(r.data?.suggested)?r.data.suggested.slice(0,12).map((x,i)=>({...x,id:x.id||`ref-${i+1}`,type:cleanType(x.type)})):[];
    return send(res,200,{...r.data,suggested,_meta:{model:r.model,usage:r.usage,mode:'reference-suggest'}});
  }
  if(b.action==='reference-build'){
    const refs=Array.isArray(b.references)?b.references.slice(0,12):[];
    if(!refs.length)return send(res,400,{error:'Add or suggest at least one reference first.'});
    const r=await callM3({system:refSystem,user:buildRefs({...b,references:refs}),temperature:.35,maxTokens:5000});
    return send(res,200,{...r.data,_meta:{model:r.model,usage:r.usage,mode:'reference-build',count:refs.length}});
  }
  return send(res,400,{error:'Unknown Reference Builder action.'});
}

function microRefs(refs=[],limit=9){const xs=refs.slice(0,limit);return xs.length?xs.map((r,i)=>`@image${i+1} = ${r.name||r.label||r.type||'reference'} | ${r.type||'other'} | ${r.consistencyLock||r.notes||r.videoUseHint||'assigned role only'}`).join('\n'):'No finished reference sheets mapped yet.'}
function microCommon(b){return`PREMISE: ${b.premise||''}\nGENRE: ${b.genre||'Drama'}\nTONE: ${b.tone||'premium mobile drama'}\nHUMAN FOCUS: ${b.humanFocus||'Human leads'}\nAVOMIEZ ROLE: ${b.avomiezRole||'Cameo / side character'}\nEPISODE LENGTH: ${b.episodeLength||60}s\nSEASON EPISODES: ${b.episodeCount||5}\nCREATOR NOTES: ${b.notes||'none'}`}
function microSeries(b){return`${microCommon(b)}\n\nBuild a compact SERIES BIBLE for a vertical micro-drama. Create immediate curiosity, recurring human relationship tension, a season-level secret/problem, escalating reveals and cliffhangers. If AvoMiez is cameo/side character, use him sparingly as observer, clue-finder, comic contrast or plot trigger.\n\nReturn exactly {"title":"","logline":"","hookPromise":"","world":"","seasonMystery":"","cast":[{"name":"","role":"lead|co-lead|antagonist|support|AvoMiez","publicFace":"","secret":"","goal":"","visualLock":""}],"relationshipEngine":[""],"recurringLocations":[""],"recurringProps":[""],"referenceNeeds":[{"name":"","type":"character|world|outfit|prop|relation","importance":"critical|high|medium","reason":""}],"episodes":[{"episode":1,"title":"","openingHook":"0-3s","story":"3-5 sentence summary","reveal":"","cliffhanger":"final turn"}],"seasonPayoff":""}. Create exactly ${Math.max(3,Math.min(10,Number(b.episodeCount)||5))} episode summaries. No filler.`}
function microEpisode(b,target){const p=target.profile,parts=splitDurations(Number(b.episodeLength)||60,p.maxDuration);return`${microCommon(b)}\nTARGET MODEL: ${p.label}\n${modelPromptGuidance(target,{duration:Number(b.episodeLength)||60,referenceCount:(b.references||[]).length,motion:false})}\nSERIES BIBLE:\n${JSON.stringify(b.seriesBible||{})}\nEPISODE:\n${JSON.stringify(b.episode||{})}\nREFERENCE MAP:\n${microRefs(b.references||[],p.imageRefs)}\n\nTurn the episode into a production plan for exactly ${b.episodeLength||60}s: cold open, conflict/context, escalation, mid-turn, emotional/apparent resolution beat, sharp reveal/cliffhanger. Human faces/relationships stay central when requested. The model requires ${parts.length} generation clips with durations ${parts.join('s + ')}s. Place boundaries at continuity-friendly action/reaction or location beats.\n\nReturn exactly {"episodeTitle":"","episodeHook":"","continuityLocks":[""],"referenceMap":["@image1 = ..."],"beats":[{"time":"0-5s","beat":"","purpose":"hook|conflict|reveal|payoff"}],"clips":[{"clip":1,"duration":${parts[0]},"storyStart":"","action":"","endBridge":"","references":["@image1"]}],"cliffhanger":"","nextEpisodeTease":""}. Return exactly ${parts.length} clips and use durations ${JSON.stringify(parts)} in order.`}
function microClip(b,target){const p=target.profile,d=Math.max(1,Number(b.clip?.duration)||Math.min(15,p.maxDuration));return`${microCommon(b)}\n${modelPromptGuidance(target,{duration:d,referenceCount:(b.references||[]).length,motion:false})}\nSERIES CONTINUITY:\n${JSON.stringify({title:b.seriesBible?.title,world:b.seriesBible?.world,cast:b.seriesBible?.cast,relationshipEngine:b.seriesBible?.relationshipEngine})}\nEPISODE PLAN:\n${JSON.stringify({episodeTitle:b.episodePlan?.episodeTitle,episodeHook:b.episodePlan?.episodeHook,continuityLocks:b.episodePlan?.continuityLocks,cliffhanger:b.episodePlan?.cliffhanger})}\nCLIP:\n${JSON.stringify(b.clip||{})}\nPREVIOUS END: ${b.previousEnd||'Opening clip.'}\nREFERENCE MAP:\n${microRefs(b.references||[],p.imageRefs)}\n\nWrite one complete production-ready ${p.label} prompt for ONLY this ${d}s clip. Begin with target model + concise reference map when references exist. Preserve identities, wardrobe/location continuity and exact end-bridge. Use 9:16, model-appropriate native audio/dialogue, clear time blocks, readable camera/action causality and one main dramatic objective. Return exactly {"prompt":"","firstFrame":"","lastFrame":"","audio":"","continuityBridge":""}.`}

export async function handleMicroAction(b,res){
  if(!String(b.premise||'').trim())return send(res,400,{error:'Add a micro-drama premise first.'});
  if(b.action==='micro-series'){const r=await callM3({system:microSystem,user:microSeries(b),temperature:.68,maxTokens:3800});return send(res,200,{...r.data,_meta:{model:r.model,usage:r.usage,mode:'micro-series'}})}
  const target=resolveTargetModel(b.targetModel||'auto',{duration:Number(b.episodeLength)||60,referenceCount:(b.references||[]).length,motion:false,audio:true});
  if(b.action==='micro-episode'){const r=await callM3({system:microSystem,user:microEpisode(b,target),temperature:.58,maxTokens:3300});return send(res,200,{...r.data,_meta:{model:r.model,usage:r.usage,mode:'micro-episode',targetModel:target.key,targetModelLabel:target.profile.label,verifiedAt:MODEL_PROFILES_VERIFIED_AT}})}
  if(b.action==='micro-clip'){if(!b.clip)return send(res,400,{error:'Clip plan missing.'});const d=Number(b.clip.duration)||Math.min(15,target.profile.maxDuration);const r=await callM3({system:microSystem,user:microClip(b,target),temperature:.5,maxTokens:3200});const data={...r.data};const fit=await enforceVideoPromptLimit(data.prompt,{label:'Micro Drama clip prompt',duration:d,maxChars:target.profile.promptMax,modelLabel:target.profile.label});data.prompt=fit.prompt;return send(res,200,{...data,_meta:{model:r.model,usage:r.usage,mode:'micro-clip',targetModel:target.key,targetModelLabel:target.profile.label,promptChars:fit.finalChars,promptHardMax:fit.hardMax,promptSoftTarget:fit.softTarget,verifiedAt:MODEL_PROFILES_VERIFIED_AT}})}
  return send(res,400,{error:'Unknown Micro Drama action.'});
}
