import{AVOMIEZ_LOCK,callM3,enforcePost,send}from'../lib/gmi.js';
import{normalizeVideoDuration,durationPromptGuidance}from'../lib/duration-policy.js';
import{normalizeToneOverlay,toneOverlayText}from'../lib/tone-overlay.js';
import{resolveTargetModel,modelPromptGuidance,MODEL_PROFILES_VERIFIED_AT}from'../lib/video-models.js';

const system=`You are the Creative Mixer / Idea Workshop inside AvoMiez Director V3.1. ${AVOMIEZ_LOCK}\nTurn a creator's RAW STORY IDEA plus CURRENT CREATIVE MIX into stronger, visually executable directions before the final production prompt is written. Preserve the creator's premise, relationships, reveals and important jokes. The selected TARGET VIDEO MODEL is part of the creative brief: shape the story so it is realistic for that model's duration, reference and audio capabilities. If the requested runtime exceeds one generation, design natural clip boundaries rather than pretending it fits. Do not flatten unusual ideas into generic cat content. Return JSON only.`;

function refsText(refs=[]){if(!refs.length)return'No image references attached.';return refs.slice(0,9).map((r,i)=>`${r.id||'@image'+(i+1)} = ${r.label||r.type||'reference'} | role: ${r.type||'other'} | instruction: ${r.hint||'use only for its assigned role'}`).join('\n')}

function user(b){
  const duration=normalizeVideoDuration(b.duration),tone=normalizeToneOverlay(b.toneOverlay),refs=Array.isArray(b.references)?b.references.slice(0,9):[];
  const target=resolveTargetModel(b.targetModel||'auto',{duration,referenceCount:refs.length,motion:!!b.motionReference,audio:String(b.audio||'').toLowerCase()!=='none'});
  return`RAW STORY IDEA:\n${String(b.idea||'').trim()}\n\nCURRENT CREATIVE MIX:\n- Duration: ${duration}s, vertical 9:16\n- Primary style / genre: ${b.style||'cinematic'}\n- Audio direction: ${b.audio||'native synchronized sound'}\n- Seamless loop requested: ${b.loop?'yes':'no / optional'}\n- Motion reference: ${b.motionReference?'yes':'none'}\n- Director notes: ${b.directorNotes||'none'}\n\n${modelPromptGuidance(target,{duration,referenceCount:refs.length,motion:!!b.motionReference})}\n\n${toneOverlayText(tone)}\n\nACTIVE REFERENCE MAP / ROLES:\n${refsText(refs)}\n\n${durationPromptGuidance(duration)}\n\nTASK:\n1. Identify the strongest hook, reveal, emotional/comedic engine and visual escalation already inside the raw idea.\n2. Develop THREE meaningfully different directions from the SAME premise: A Viral/Punchy, B Cinematic Story, C Wildcard.\n3. Every direction must use the CURRENT CREATIVE MIX and TARGET VIDEO MODEL.\n4. If the target model cannot do ${duration}s in one generation, make the beat sheet naturally split-ready across multiple clips without changing the requested total story duration.\n5. Respect reference roles and actual model reference capacity.\n6. Do NOT write the final generation prompt yet.\n\nReturn exactly {"mixSummary":"one concise line including target model","targetModel":"${target.profile.label}","modelFit":"short explanation of fit/limits","coreEngine":{"hook":"","secretOrReveal":"","relationship":"","escalation":"","payoff":""},"variants":[{"id":"A","title":"","strength":"Viral / Punchy","hook":"0-2s hook","story":"complete upgraded editable story in 3-6 concise sentences","beats":[{"time":"0-3s","beat":""}],"whyItWorks":"","directorNote":"short note to carry into final Director prompt"},{"id":"B","title":"","strength":"Cinematic Story","hook":"","story":"","beats":[{"time":"0-3s","beat":""}],"whyItWorks":"","directorNote":""},{"id":"C","title":"","strength":"Wildcard","hook":"","story":"","beats":[{"time":"0-3s","beat":""}],"whyItWorks":"","directorNote":""}],"recommendedVariant":"A|B|C","recommendationWhy":"one concise sentence"}. Beat timing for each variant must cover the full ${duration}s with no gaps, but stay concise.`;
}

export default async function handler(req,res){if(!enforcePost(req,res))return;try{
  const b=req.body||{};if(!String(b.idea||'').trim())return send(res,400,{error:'Write your story idea first.'});
  const refs=Array.isArray(b.references)?b.references.slice(0,9):[],imgs=Array.isArray(b.referenceImages)?b.referenceImages.slice(0,9):[],duration=normalizeVideoDuration(b.duration);
  const target=resolveTargetModel(b.targetModel||'auto',{duration,referenceCount:refs.length,motion:!!b.motionReference,audio:String(b.audio||'').toLowerCase()!=='none'});
  const prompt=user({...b,references:refs});let r;
  if(imgs.length){const content=[{type:'text',text:prompt}];imgs.forEach((url,i)=>{if(typeof url!=='string'||!url.startsWith('data:image/'))return;content.push({type:'text',text:`Creative Mixer reference ${i+1}: ${refs[i]?.id||'@image'+(i+1)} = ${refs[i]?.label||refs[i]?.type||'reference'}; role ${refs[i]?.type||'other'}.`});content.push({type:'image_url',image_url:{url},detail:'low'})});r=await callM3({messages:[{role:'system',content:system},{role:'user',content}],temperature:.72,maxTokens:3300})}
  else r=await callM3({system,user:prompt,temperature:.72,maxTokens:3000});
  return send(res,200,{...r.data,_meta:{model:r.model,usage:r.usage,duration,referencesAnalyzed:imgs.length,toneOverlay:normalizeToneOverlay(b.toneOverlay),targetModel:target.key,targetModelLabel:target.profile.label,targetRequested:target.requested,targetMaxDuration:target.profile.maxDuration,targetPromptMax:target.profile.promptMax,modelProfilesVerifiedAt:MODEL_PROFILES_VERIFIED_AT,modelRecommendation:target.recommendation}})
}catch(e){return send(res,500,{error:e.message||'Idea development failed'})}}
