import{AVOMIEZ_LOCK,callM3,enforcePost,send}from'../lib/gmi.js';
import{VIDEO_PROMPT_MAX_CHARS,enforceVideoPromptLimit}from'../lib/prompt-limit.js';
import{toneOverlayText,normalizeToneOverlay}from'../lib/tone-overlay.js';
import{normalizeVideoDuration,shotCountForDuration,durationPromptGuidance,softPromptTargetForDuration}from'../lib/duration-policy.js';
import{resolveTargetModel,modelPromptGuidance,splitDurations,MODEL_PROFILES_VERIFIED_AT}from'../lib/video-models.js';

const system=`You are AvoMiez Director V3.1, a model-aware planning engine for production-ready AI video generation. ${AVOMIEZ_LOCK}\nYou receive a TARGET VIDEO MODEL profile and must translate the same creative intent into that model's preferred prompting style. Never invent capabilities the selected model does not have. If requested runtime exceeds the target model's single-generation duration, split the story into continuity-safe clips and return one prompt per clip. Keep character/reference identity stable across parts. You may receive image references, sampled motion-reference frames and a SECONDARY TONE OVERLAY. Character references are identity anchors; scene/style/prop/vehicle/outfit references only affect assigned roles. Longer duration must NOT create bloated prose. All prompts obey the target model prompt cap and the app-wide 5000-character ceiling. Return JSON only.`;

function refText(refs=[]){if(!refs.length)return'No additional image references supplied.';return refs.map((r,i)=>`${r.id||'@image'+(i+1)} = ${r.label||r.type||'reference'} | role: ${r.type||'other'} | instruction: ${r.hint||'use only for its assigned purpose'}`).join('\n')}
function motionText(m){if(!m)return'No motion-reference video supplied.';return`@video1 = motion / choreography reference. PRESET: ${m.preset||'balanced'}. PRESERVE: ${(m.preserve||[]).join(', ')||'general motion mechanics'}. NOTE: ${m.note||'none'}. INSTRUCTIONS: ${m.instructions||'Use motion, camera and timing as a blueprint only.'}`}

function user({idea,duration=12,style='cinematic',audio='native sound',loop=true,creatorNote='',references=[],motionReference=null,motionFrames=[],toneOverlay={},target}){
  const d=normalizeVideoDuration(duration),shots=shotCountForDuration(d),soft=softPromptTargetForDuration(d),parts=splitDurations(d,target.profile.maxDuration);
  return`Create a production-ready VIDEO PLAN optimized for the selected target model.\n\nIDEA: ${idea}.\nPRIMARY GENRE / STYLE: ${style}.\nREQUESTED STORY RUNTIME: ${d}s vertical 9:16.\nAUDIO: ${audio}.\nLOOP: ${loop?'yes / desirable':'optional'}.\nCREATOR DIRECTION: ${creatorNote||'none'}.\n\n${modelPromptGuidance(target,{duration:d,referenceCount:references.length,motion:!!motionReference})}\n\n${toneOverlayText(toneOverlay)}\n\nREFERENCE MAP:\n${refText(references)}\n\nMOTION REFERENCE:\n${motionText(motionReference)}\nThere are ${Array.isArray(motionFrames)?motionFrames.length:0} sampled motion keyframes attached when available. Infer only motion/camera/timing visually supported by them.\n\n${durationPromptGuidance(d)}\nGENERAL PROMPT RULE: app-wide maximum ${VIDEO_PROMPT_MAX_CHARS} chars; target-model maximum ${target.profile.promptMax} chars. Preserve target-model instructions, identity locks, supported reference IDs, tone, timing and core choreography.\n\nSPLIT POLICY: requested runtime ${d}s; target single-generation max ${target.profile.maxDuration}s; required clip durations = ${parts.join(', ')} seconds. ${parts.length>1?'h3Prompt MUST be the complete prompt for CLIP 1 only. continuationPrompts MUST contain one complete model-ready prompt for every remaining clip, with a concise continuity bridge at the top of each. Do not write a fake single '+d+'s prompt.':'continuationPrompts must be an empty array.'}\n\nReturn exactly {\n"summary":"overall story summary",\n"hook":"opening hook",\n"shots":[{"number":1,"start":0,"end":0,"camera":"","action":"","payoff":""}],\n"characterLock":[""],\n"referenceCheck":["short checks/warnings"],\n"toneApplication":["2-4 concise notes"],\n"motionBlueprint":[{"time":"0.0-0.0s","motion":"","camera":"","timing":""}],\n"modelOptimization":{"targetModel":"${target.profile.label}","why":"how the prompt was adapted to this model","durationFit":"","referenceFit":""},\n"generationPlan":[{"part":1,"duration":${parts[0]||d},"purpose":"","continuityBridge":""}],\n"h3Prompt":"complete target-model-optimized prompt for clip 1, within the target prompt cap",\n"continuationPrompts":[{"part":2,"duration":0,"prompt":"complete target-model-optimized continuation prompt"}],\n"failureRisks":["5 items"],\n"improvements":["5 items"],\n"loopStrategy":""\n}.\nUse about ${shots} overall story beats across the requested ${d}s. If split, distribute them logically across clips. If no split, continuationPrompts must be [].`}

export default async function handler(req,res){if(!enforcePost(req,res))return;try{
  const b=req.body||{};if(!b.idea)return send(res,400,{error:'Please enter a video idea.'});
  const duration=normalizeVideoDuration(b.duration),refs=Array.isArray(b.references)?b.references.slice(0,9):[],refImages=Array.isArray(b.referenceImages)?b.referenceImages.slice(0,9):[],motionFrames=Array.isArray(b.motionFrames)?b.motionFrames.slice(0,5):[],tone=normalizeToneOverlay(b.toneOverlay);
  const target=resolveTargetModel(b.targetModel||'auto',{duration,referenceCount:refs.length,motion:!!b.motionReference,audio:String(b.audio||'').toLowerCase()!=='none'});
  const prompt=user({...b,duration,references:refs,motionFrames,toneOverlay:tone,target});let r;
  if(refImages.length||motionFrames.length){const content=[{type:'text',text:prompt}];refImages.forEach((url,i)=>{content.push({type:'text',text:`Reference image ${i+1}: ${(refs[i]?.id||'@image'+(i+1))} = ${refs[i]?.label||refs[i]?.type||'reference'}; role ${refs[i]?.type||'other'}.`});content.push({type:'image_url',image_url:{url},detail:'low'})});if(motionFrames.length){content.push({type:'text',text:'Chronological sampled keyframes from @video1. Use only for motion/choreography/camera/timing requested by the creator.'});motionFrames.forEach((url,i)=>{content.push({type:'text',text:`@video1 sampled keyframe ${i+1}/${motionFrames.length}.`});content.push({type:'image_url',image_url:{url},detail:'low'})})}r=await callM3({messages:[{role:'system',content:system},{role:'user',content}],temperature:.5,maxTokens:4300})}
  else r=await callM3({system,user:prompt,temperature:.5,maxTokens:3900});
  const data={...r.data};
  const fit=await enforceVideoPromptLimit(data.h3Prompt,{label:'primary video prompt',duration:Math.min(duration,target.profile.maxDuration),maxChars:target.profile.promptMax,modelLabel:target.profile.label});data.h3Prompt=fit.prompt;
  const cont=[];for(const item of(Array.isArray(data.continuationPrompts)?data.continuationPrompts:[])){const cd=Math.min(Number(item.duration)||target.profile.maxDuration,target.profile.maxDuration);const cf=await enforceVideoPromptLimit(item.prompt,{label:`continuation part ${item.part||cont.length+2}`,duration:cd,maxChars:target.profile.promptMax,modelLabel:target.profile.label});cont.push({...item,duration:cd,prompt:cf.prompt,promptChars:cf.finalChars});}data.continuationPrompts=cont;
  return send(res,200,{...data,_meta:{model:r.model,usage:r.usage,duration,targetModel:target.key,targetModelLabel:target.profile.label,targetRequested:target.requested,targetPromptMax:target.profile.promptMax,targetMaxDuration:target.profile.maxDuration,modelProfilesVerifiedAt:MODEL_PROFILES_VERIFIED_AT,modelRecommendation:target.recommendation,referencesAnalyzed:refImages.length,motionFramesAnalyzed:motionFrames.length,toneOverlay:tone,promptLimit:target.profile.promptMax,promptChars:fit.finalChars,promptOriginalChars:fit.originalChars,promptCompacted:fit.compacted,promptCompaction:fit.method}})
}catch(e){return send(res,500,{error:e.message||'Unexpected server error'})}}
