import{AVOMIEZ_LOCK,callM3,enforcePost,send}from'../lib/gmi.js';
import{VIDEO_PROMPT_MAX_CHARS,enforceVideoPromptLimit}from'../lib/prompt-limit.js';
import{toneOverlayText,normalizeToneOverlay}from'../lib/tone-overlay.js';
import{normalizeVideoDuration,durationPromptGuidance}from'../lib/duration-policy.js';
import{resolveTargetModel,modelPromptGuidance,MODEL_PROFILES_VERIFIED_AT}from'../lib/video-models.js';
const system=`You are the refinement editor inside AvoMiez Director V3.1. ${AVOMIEZ_LOCK}\nImprove exactly one requested quality while preserving story, identity, duration, 9:16 format, reference roles, active tone overlay and the selected TARGET VIDEO MODEL's prompt strategy/capabilities. Do not undo model-specific optimization. Return JSON only.`;
const modeRules={funnier:'Increase deadpan visual comedy, contrast, timing and payoff without forced dialogue.',cinematic:'Increase composition, camera choreography, lighting, depth and payoff without prompt bloat.',action:'Increase readable physical action and momentum while staying feasible.',loop:'Make the ending naturally reconnect to the opening when appropriate.',simplify:'Reduce risk: remove redundancy, competing actions and unnecessary jargon while preserving core beats.'};
function user(b,target){const d=normalizeVideoDuration(b.duration),rule=modeRules[b.mode]||modeRules.simplify;return`REFINEMENT MODE: ${b.mode}\nINSTRUCTION: ${rule}\n\n${modelPromptGuidance(target,{duration:d,referenceCount:0,motion:false})}\n\n${toneOverlayText(b.toneOverlay)}\nCURRENT IDEA:\n${b.idea||''}\nCURRENT PROMPT:\n${b.currentPrompt||''}\nTARGET CLIP: ${d}s, 9:16, style ${b.style||'cinematic'}, audio ${b.audio||'native synchronized sound'}, loop ${b.loop?'yes':'optional'}.\n${durationPromptGuidance(d)}\nReturn exactly {"h3Prompt":"complete replacement prompt optimized for ${target.profile.label}","changeSummary":"one concise sentence"}. Keep reference IDs and AvoMiez identity intact. Hard prompt cap for this target: ${target.profile.promptMax}; app ceiling: ${VIDEO_PROMPT_MAX_CHARS}.`}
export default async function handler(req,res){if(!enforcePost(req,res))return;try{const b=req.body||{};if(!b.currentPrompt)return send(res,400,{error:'No prompt available to improve.'});const duration=normalizeVideoDuration(b.duration),tone=normalizeToneOverlay(b.toneOverlay),target=resolveTargetModel(b.targetModel||'auto',{duration,referenceCount:0,motion:false,audio:true});const r=await callM3({system,user:user({...b,duration,toneOverlay:tone},target),temperature:.45,maxTokens:2900});const data={...r.data};const fit=await enforceVideoPromptLimit(data.h3Prompt,{label:'refined video prompt',duration:Math.min(duration,target.profile.maxDuration),maxChars:target.profile.promptMax,modelLabel:target.profile.label});data.h3Prompt=fit.prompt;return send(res,200,{...data,_meta:{model:r.model,usage:r.usage,duration,toneOverlay:tone,targetModel:target.key,targetModelLabel:target.profile.label,targetPromptMax:target.profile.promptMax,modelProfilesVerifiedAt:MODEL_PROFILES_VERIFIED_AT,promptChars:fit.finalChars,promptCompacted:fit.compacted}})}catch(e){return send(res,500,{error:e.message||'Unexpected server error'})}}
