import{AVOMIEZ_LOCK,callM3,enforcePost,send}from'../lib/gmi.js';
import{resolveTargetModel,splitDurations,modelPromptGuidance,MODEL_PROFILES_VERIFIED_AT}from'../lib/video-models.js';
import{enforceVideoPromptLimit}from'../lib/prompt-limit.js';

const system=`You are the Micro Drama Studio inside AvoMiez Director V3.3. You create mobile-first 9:16 serialized micro-dramas with strong human-led character conflict, secrets, reversals, cliffhangers and visual continuity. ${AVOMIEZ_LOCK}\nAvoMiez may be absent, cameo, sidekick, co-lead or lead depending on the creator setting. Do not force him into every beat. Preserve recurring cast, wardrobe, locations and props through explicit reference maps. Episodes may be 30-120 seconds and MUST be divided into target-model-compatible generation clips. Never claim guaranteed virality. Return JSON only.`;

function refsText(refs=[],limit=9){const xs=refs.slice(0,limit);return xs.length?xs.map((r,i)=>`@image${i+1} = ${r.name||r.label||r.type||'reference'} | ${r.type||'other'} | ${r.consistencyLock||r.notes||r.videoUseHint||'use only for its assigned role'}`).join('\n'):'No finished reference sheets mapped yet.'}
function common(b){return`PREMISE: ${b.premise||''}\nGENRE: ${b.genre||'Drama'}\nTONE: ${b.tone||'premium mobile drama'}\nHUMAN FOCUS: ${b.humanFocus||'Human leads'}\nAVOMIEZ ROLE: ${b.avomiezRole||'Cameo / side character'}\nEPISODE LENGTH: ${b.episodeLength||60}s\nSEASON EPISODES: ${b.episodeCount||5}\nCREATOR NOTES: ${b.notes||'none'}`}

function seriesPrompt(b){return`${common(b)}\n\nTASK: Build a compact SERIES BIBLE for a vertical micro-drama. The premise must create immediate curiosity, recurring human relationship tension, a season-level secret/problem, escalating reveals and cliffhangers. Keep AvoMiez in the chosen role; if he is a cameo/side character, use him sparingly as observer, clue-finder, comic contrast or plot trigger.\n\nReturn exactly {"title":"","logline":"","hookPromise":"what viewers repeatedly come back for","world":"recurring setting and visual identity","seasonMystery":"","cast":[{"name":"","role":"lead|co-lead|antagonist|support|AvoMiez","publicFace":"","secret":"","goal":"","visualLock":"stable visual traits/reference needs"}],"relationshipEngine":["key relationship tension"],"recurringLocations":[""],"recurringProps":[""],"referenceNeeds":[{"name":"","type":"character|world|outfit|prop|relation","importance":"critical|high|medium","reason":""}],"episodes":[{"episode":1,"title":"","openingHook":"0-3s","story":"3-5 sentence episode summary","reveal":"","cliffhanger":"final 3-8s turn"}],"seasonPayoff":""}. Create exactly ${Math.max(3,Math.min(10,Number(b.episodeCount)||5))} episode summaries. Every episode must advance the central story; no filler.`}

function episodePrompt(b,target){const profile=target.profile,parts=splitDurations(Number(b.episodeLength)||60,profile.maxDuration);return`${common(b)}\nTARGET MODEL: ${profile.label}\n${modelPromptGuidance(target,{duration:Number(b.episodeLength)||60,referenceCount:(b.references||[]).length,motion:false})}\n\nSERIES BIBLE:\n${JSON.stringify(b.seriesBible||{})}\n\nEPISODE TO DEVELOP:\n${JSON.stringify(b.episode||{})}\n\nACTIVE REFERENCE MAP:\n${refsText(b.references||[],profile.imageRefs)}\n\nTASK: Turn this episode summary into a production plan for exactly ${b.episodeLength||60}s. Use fast mobile-drama storytelling: cold open, conflict/context, escalation, mid-episode turn, apparent resolution or emotional beat, then a sharp reveal/cliffhanger. Human faces/relationships should remain the dramatic center when Human Focus says so.\n\nThe selected model requires ${parts.length} generation clip${parts.length===1?'':'s'} with durations ${parts.join('s + ')}s. Design clip boundaries at continuity-friendly action/reaction or location beats.\n\nReturn exactly {"episodeTitle":"","episodeHook":"","continuityLocks":[""],"referenceMap":["@image1 = ..."],"beats":[{"time":"0-5s","beat":"","purpose":"hook|conflict|reveal|payoff"}],"clips":[{"clip":1,"duration":${parts[0]},"storyStart":"what is true at first frame","action":"complete story beat for this clip","endBridge":"exact visual/emotional state to continue from","references":["@image1"]}],"cliffhanger":"","nextEpisodeTease":""}. Return exactly ${parts.length} clips and use durations ${JSON.stringify(parts)} in order.`}

function clipPrompt(b,target){const profile=target.profile,d=Math.max(1,Number(b.clip?.duration)||Math.min(15,profile.maxDuration));return`${common(b)}\n\n${modelPromptGuidance(target,{duration:d,referenceCount:(b.references||[]).length,motion:false})}\n\nSERIES CONTINUITY:\n${JSON.stringify({title:b.seriesBible?.title,world:b.seriesBible?.world,cast:b.seriesBible?.cast,relationshipEngine:b.seriesBible?.relationshipEngine})}\n\nEPISODE PLAN:\n${JSON.stringify({episodeTitle:b.episodePlan?.episodeTitle,episodeHook:b.episodePlan?.episodeHook,continuityLocks:b.episodePlan?.continuityLocks,cliffhanger:b.episodePlan?.cliffhanger})}\n\nCLIP TO GENERATE:\n${JSON.stringify(b.clip||{})}\n\nPREVIOUS CLIP END STATE: ${b.previousEnd||'This is the opening clip.'}\n\nREFERENCE MAP:\n${refsText(b.references||[],profile.imageRefs)}\n\nTASK: Write one complete production-ready ${profile.label} video prompt for this ${d}s clip. Begin with TARGET MODEL + concise REFERENCE MAP when references exist. Preserve human identities, wardrobe/location continuity and exact end-bridge. Use 9:16, model-appropriate native audio/dialogue direction, clear time blocks, readable camera/action causality and one main dramatic objective. Do not summarize the whole episode; render ONLY this clip. End at the precise continuity state needed for the next clip or the episode cliffhanger. Return exactly {"prompt":"","firstFrame":"","lastFrame":"","audio":"","continuityBridge":""}.`}

export default async function handler(req,res){if(!enforcePost(req,res))return;try{const b=req.body||{},action=String(b.action||'series');if(!String(b.premise||'').trim())return send(res,400,{error:'Add a micro-drama premise first.'});
  if(action==='series'){const r=await callM3({system,user:seriesPrompt(b),temperature:.68,maxTokens:3800});return send(res,200,{...r.data,_meta:{model:r.model,usage:r.usage,mode:'series'}})}
  const target=resolveTargetModel(b.targetModel||'auto',{duration:Number(b.episodeLength)||60,referenceCount:(b.references||[]).length,motion:false,audio:true});
  if(action==='episode'){const r=await callM3({system,user:episodePrompt(b,target),temperature:.58,maxTokens:3300});return send(res,200,{...r.data,_meta:{model:r.model,usage:r.usage,mode:'episode',targetModel:target.key,targetModelLabel:target.profile.label,verifiedAt:MODEL_PROFILES_VERIFIED_AT}})}
  if(action==='clip'){if(!b.clip)return send(res,400,{error:'Clip plan missing.'});const d=Number(b.clip.duration)||Math.min(15,target.profile.maxDuration);const r=await callM3({system,user:clipPrompt(b,target),temperature:.5,maxTokens:3200});const data={...r.data};const fit=await enforceVideoPromptLimit(data.prompt,{label:'Micro Drama clip prompt',duration:d,maxChars:target.profile.promptMax,modelLabel:target.profile.label});data.prompt=fit.prompt;return send(res,200,{...data,_meta:{model:r.model,usage:r.usage,mode:'clip',targetModel:target.key,targetModelLabel:target.profile.label,promptChars:fit.finalChars,promptHardMax:fit.hardMax,promptSoftTarget:fit.softTarget,verifiedAt:MODEL_PROFILES_VERIFIED_AT}})}
  return send(res,400,{error:'Unknown Micro Drama action.'});
}catch(e){return send(res,500,{error:e.message||'Micro Drama Studio failed'})}}
