import{AVOMIEZ_LOCK,callM3,enforcePost,send}from'../lib/gmi.js';

const TYPES=['character','world','outfit','prop','relation'];
const system=`You are the Reference Builder inside AvoMiez Director V3.3. You design practical visual-reference packs for recurring AI-video stories and micro-dramas. ${AVOMIEZ_LOCK}\nYour job is to decide which reference images/sheets are actually useful for continuity across many clips, then write production-ready image-generation prompts for those references. Favor human-led drama when requested; AvoMiez may be cameo, side character, co-lead or lead. Keep identities, wardrobes, recurring locations and story-critical props easy to reuse across Seedance, Kling, MiniMax H3, PixVerse and similar reference-to-video workflows. Avoid needless reference bloat. Return JSON only.`;

function cleanType(v){v=String(v||'').toLowerCase();return TYPES.includes(v)?v:'prop'}
function storyContext(b){return`SERIES / STORY PREMISE:\n${String(b.story||'').trim()}\n\nGENRE: ${b.genre||'drama'}\nTONE / FLAVOR: ${b.tone||'balanced'}\nHUMAN FOCUS: ${b.humanFocus||'human leads'}\nAVOMIEZ ROLE: ${b.avomiezRole||'side character / cameo'}\nSERIES SCALE: ${b.seriesScale||'multi-episode short-form series'}\nCREATOR NOTES: ${b.notes||'none'}`}

function suggestPrompt(b){return`${storyContext(b)}\n\nTASK: Build a lean REFERENCE FOUNDATION for this story. Suggest only references that are likely to recur or matter for continuity. Think in five groups: CHARACTER, WORLD, OUTFIT, PROP, RELATION.\n\nRules:\n- Human leads should receive stable character master sheets when they recur.\n- AvoMiez gets a reference only if his selected role makes him visually relevant.\n- Recurring locations should get environment/world sheets; one-off locations usually should not.\n- Outfit sheets are for signature or repeated outfits, transformations, uniforms, wedding looks, horror damage states, etc.\n- Props only if story-critical or repeatedly visible.\n- Relation sheets are useful when two recurring characters need stable height/proportion/chemistry/blocking together.\n- Prefer 5-10 strong references over 20 weak ones.\n- Do not invent copyrighted characters or brands.\n\nReturn exactly {"packTitle":"","strategy":"2-4 concise sentences","suggested":[{"id":"ref-1","name":"","type":"character|world|outfit|prop|relation","recurring":true,"importance":"critical|high|medium|optional","reason":"why this reference helps continuity","notes":"what must be visually locked","videoUse":"how later video prompts should use this reference"}],"missingQuestions":["only questions that would materially improve visual consistency"]}.`}

function buildPrompt(b){const refs=(Array.isArray(b.references)?b.references:[]).slice(0,20).map((r,i)=>({id:r.id||`ref-${i+1}`,name:r.name||`Reference ${i+1}`,type:cleanType(r.type),recurring:r.recurring!==false,importance:r.importance||'high',notes:r.notes||'',reason:r.reason||'',videoUse:r.videoUse||''}));return`${storyContext(b)}\n\nREFERENCE ENTRIES TO BUILD:\n${JSON.stringify(refs)}\n\nTASK: Write one polished IMAGE-GENERATION PROMPT for every reference entry. These prompts will commonly be copied into ChatGPT image generation or another high-quality image model, then the finished sheet/image will be uploaded back into AvoMiez Director.\n\nPROMPT RULES BY TYPE:\nCHARACTER — clean professional photorealistic master sheet; same identity in every panel; front, 3/4, side, full-body, face close-up, neutral expression plus one useful story expression; readable clothing/body/face traits; neutral studio background; no text needed unless tiny labels help layout.\nWORLD — environment reference board with establishing wide, medium spatial view, key recurring angle/details, coherent architecture/materials/lighting, no people unless scale silhouettes are necessary; preserve geography/layout.\nOUTFIT — same assigned character identity, front/3/4/back or useful garment views, materials, fit, accessories, footwear, damage/state if story-relevant; neutral background; do not redesign the person.\nPROP — product/prop reference sheet showing hero view, side/details/scale cues and exact distinctive features; neutral background; no branding unless creator supplied it.\nRELATION — two specified recurring characters together, stable height/proportion, face identity, wardrobe baseline, neutral standing two-shot plus one story-relevant interaction/blocking pose; clean background; no romantic/physical detail beyond the story need.\n\nGENERAL:\n- Photorealistic, cinematic-real-world identity reference quality, not concept-art stylization unless the story explicitly requires it.\n- Make the prompt usable without hidden context: name the role and all important visual locks.\n- Avoid overstuffed sheets; clarity and identity consistency matter more than decoration.\n- For AvoMiez, preserve natural feline anatomy and his established identity/accessories unless creator notes intentionally request a temporary costume.\n- Add a concise CONSISTENCY LOCK and VIDEO USE HINT for each output.\n\nReturn exactly {"packTitle":"","items":[{"id":"","name":"","type":"character|world|outfit|prop|relation","imagePrompt":"complete copy-ready prompt","consistencyLock":"short visual lock to reuse across episodes","videoUseHint":"short instruction for mapping this finished reference in video prompts","suggestedFileName":"safe-short-filename.png"}]}.`}

export default async function handler(req,res){
  if(!enforcePost(req,res))return;
  try{
    const b=req.body||{},action=String(b.action||'suggest');
    if(!String(b.story||'').trim())return send(res,400,{error:'Add a series/story premise first.'});
    if(action==='suggest'){
      const r=await callM3({system,user:suggestPrompt(b),temperature:.45,maxTokens:2600});
      const suggested=Array.isArray(r.data?.suggested)?r.data.suggested.slice(0,12).map((x,i)=>({...x,id:x.id||`ref-${i+1}`,type:cleanType(x.type)})):[];
      return send(res,200,{...r.data,suggested,_meta:{model:r.model,usage:r.usage,mode:'suggest'}});
    }
    if(action==='build'){
      const refs=Array.isArray(b.references)?b.references.slice(0,20):[];
      if(!refs.length)return send(res,400,{error:'Add or suggest at least one reference first.'});
      const r=await callM3({system,user:buildPrompt({...b,references:refs}),temperature:.35,maxTokens:5200});
      return send(res,200,{...r.data,_meta:{model:r.model,usage:r.usage,mode:'build',count:refs.length}});
    }
    return send(res,400,{error:'Unknown Reference Builder action.'});
  }catch(e){return send(res,500,{error:e.message||'Reference Builder failed'})}
}
